### ISSUE TITLE
docker etcdkeeper not work

### ISSUE THREAD

**Issue by visteras** [evildecay/etcdkeeper#32]
I use Docker Swarm for start keeper:
```yaml
version: '3.3'
networks:
  net-etcd:
    external: true
services:
  keeper:
    image: evildecay/etcdkeeper:latest
    networks:
     - net-etcd
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.services.etcd-ui.loadbalancer.server.port: 8080
        
        traefik.http.routers.etcd-ui.rule: Host(`etcd.example.com`)
        traefik.http.routers.etcd-ui.middlewares: redirect@file
        traefik.http.routers.etcd-ui.entrypoints: http
        
        traefik.http.routers.etcd-ui-ssl.rule: Host(`etcd.example.com`)
        traefik.http.routers.etcd-ui-ssl.tls: 'true'
        traefik.http.routers.etcd-ui-ssl.service: etcd-ui
        traefik.http.routers.etcd-ui-ssl.tls.certresolver: default
        traefik.http.routers.etcd-ui-ssl.entrypoints: https
      restart_policy:
        condition: on-failure
        window: 120s
        max_attempts: 5
```
and after start container i see:
```
# docker logs -f etcd-ui_keeper.1.qftkn42c8m01pfhqhrdsq9g3x
2019-11-21 20:04:44.890346 I | listening on 0.0.0.0:8080
```
But i cant open etcd.example.com/etcdkeeper ... i got `Gateway Timeout` from traefik.
Any ideas?
